image: node:lts

stages:
  - install
  - build


install:
  stage: install
  script:
    - npm install
  artifacts:
    name: "artifacts"
    untracked: true
    expire_in: 60 mins
    paths:
      - .npm/
      - node_modules/

build:
  stage: build
  script:
    - CI=false npm run build
  artifacts:
    paths:
      - build
    expire_in: 60 mins
  dependencies:
    - install
